# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/carlos/dev/github.com/sigzegv/quakespasm-spiked-x

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/carlos/dev/github.com/sigzegv/quakespasm-spiked-x

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/carlos/dev/github.com/sigzegv/quakespasm-spiked-x/CMakeFiles /home/carlos/dev/github.com/sigzegv/quakespasm-spiked-x//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/carlos/dev/github.com/sigzegv/quakespasm-spiked-x/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named quakespasm

# Build rule for target.
quakespasm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quakespasm
.PHONY : quakespasm

# fast build rule for target.
quakespasm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/build
.PHONY : quakespasm/fast

Quake/bgmusic.o: Quake/bgmusic.c.o
.PHONY : Quake/bgmusic.o

# target to build an object file
Quake/bgmusic.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/bgmusic.c.o
.PHONY : Quake/bgmusic.c.o

Quake/bgmusic.i: Quake/bgmusic.c.i
.PHONY : Quake/bgmusic.i

# target to preprocess a source file
Quake/bgmusic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/bgmusic.c.i
.PHONY : Quake/bgmusic.c.i

Quake/bgmusic.s: Quake/bgmusic.c.s
.PHONY : Quake/bgmusic.s

# target to generate assembly for a file
Quake/bgmusic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/bgmusic.c.s
.PHONY : Quake/bgmusic.c.s

Quake/cd_sdl.o: Quake/cd_sdl.c.o
.PHONY : Quake/cd_sdl.o

# target to build an object file
Quake/cd_sdl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cd_sdl.c.o
.PHONY : Quake/cd_sdl.c.o

Quake/cd_sdl.i: Quake/cd_sdl.c.i
.PHONY : Quake/cd_sdl.i

# target to preprocess a source file
Quake/cd_sdl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cd_sdl.c.i
.PHONY : Quake/cd_sdl.c.i

Quake/cd_sdl.s: Quake/cd_sdl.c.s
.PHONY : Quake/cd_sdl.s

# target to generate assembly for a file
Quake/cd_sdl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cd_sdl.c.s
.PHONY : Quake/cd_sdl.c.s

Quake/cfgfile.o: Quake/cfgfile.c.o
.PHONY : Quake/cfgfile.o

# target to build an object file
Quake/cfgfile.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cfgfile.c.o
.PHONY : Quake/cfgfile.c.o

Quake/cfgfile.i: Quake/cfgfile.c.i
.PHONY : Quake/cfgfile.i

# target to preprocess a source file
Quake/cfgfile.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cfgfile.c.i
.PHONY : Quake/cfgfile.c.i

Quake/cfgfile.s: Quake/cfgfile.c.s
.PHONY : Quake/cfgfile.s

# target to generate assembly for a file
Quake/cfgfile.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cfgfile.c.s
.PHONY : Quake/cfgfile.c.s

Quake/chase.o: Quake/chase.c.o
.PHONY : Quake/chase.o

# target to build an object file
Quake/chase.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/chase.c.o
.PHONY : Quake/chase.c.o

Quake/chase.i: Quake/chase.c.i
.PHONY : Quake/chase.i

# target to preprocess a source file
Quake/chase.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/chase.c.i
.PHONY : Quake/chase.c.i

Quake/chase.s: Quake/chase.c.s
.PHONY : Quake/chase.s

# target to generate assembly for a file
Quake/chase.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/chase.c.s
.PHONY : Quake/chase.c.s

Quake/cl_demo.o: Quake/cl_demo.c.o
.PHONY : Quake/cl_demo.o

# target to build an object file
Quake/cl_demo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cl_demo.c.o
.PHONY : Quake/cl_demo.c.o

Quake/cl_demo.i: Quake/cl_demo.c.i
.PHONY : Quake/cl_demo.i

# target to preprocess a source file
Quake/cl_demo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cl_demo.c.i
.PHONY : Quake/cl_demo.c.i

Quake/cl_demo.s: Quake/cl_demo.c.s
.PHONY : Quake/cl_demo.s

# target to generate assembly for a file
Quake/cl_demo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cl_demo.c.s
.PHONY : Quake/cl_demo.c.s

Quake/cl_input.o: Quake/cl_input.c.o
.PHONY : Quake/cl_input.o

# target to build an object file
Quake/cl_input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cl_input.c.o
.PHONY : Quake/cl_input.c.o

Quake/cl_input.i: Quake/cl_input.c.i
.PHONY : Quake/cl_input.i

# target to preprocess a source file
Quake/cl_input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cl_input.c.i
.PHONY : Quake/cl_input.c.i

Quake/cl_input.s: Quake/cl_input.c.s
.PHONY : Quake/cl_input.s

# target to generate assembly for a file
Quake/cl_input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cl_input.c.s
.PHONY : Quake/cl_input.c.s

Quake/cl_main.o: Quake/cl_main.c.o
.PHONY : Quake/cl_main.o

# target to build an object file
Quake/cl_main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cl_main.c.o
.PHONY : Quake/cl_main.c.o

Quake/cl_main.i: Quake/cl_main.c.i
.PHONY : Quake/cl_main.i

# target to preprocess a source file
Quake/cl_main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cl_main.c.i
.PHONY : Quake/cl_main.c.i

Quake/cl_main.s: Quake/cl_main.c.s
.PHONY : Quake/cl_main.s

# target to generate assembly for a file
Quake/cl_main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cl_main.c.s
.PHONY : Quake/cl_main.c.s

Quake/cl_parse.o: Quake/cl_parse.c.o
.PHONY : Quake/cl_parse.o

# target to build an object file
Quake/cl_parse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cl_parse.c.o
.PHONY : Quake/cl_parse.c.o

Quake/cl_parse.i: Quake/cl_parse.c.i
.PHONY : Quake/cl_parse.i

# target to preprocess a source file
Quake/cl_parse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cl_parse.c.i
.PHONY : Quake/cl_parse.c.i

Quake/cl_parse.s: Quake/cl_parse.c.s
.PHONY : Quake/cl_parse.s

# target to generate assembly for a file
Quake/cl_parse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cl_parse.c.s
.PHONY : Quake/cl_parse.c.s

Quake/cl_tent.o: Quake/cl_tent.c.o
.PHONY : Quake/cl_tent.o

# target to build an object file
Quake/cl_tent.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cl_tent.c.o
.PHONY : Quake/cl_tent.c.o

Quake/cl_tent.i: Quake/cl_tent.c.i
.PHONY : Quake/cl_tent.i

# target to preprocess a source file
Quake/cl_tent.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cl_tent.c.i
.PHONY : Quake/cl_tent.c.i

Quake/cl_tent.s: Quake/cl_tent.c.s
.PHONY : Quake/cl_tent.s

# target to generate assembly for a file
Quake/cl_tent.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cl_tent.c.s
.PHONY : Quake/cl_tent.c.s

Quake/cmd.o: Quake/cmd.c.o
.PHONY : Quake/cmd.o

# target to build an object file
Quake/cmd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cmd.c.o
.PHONY : Quake/cmd.c.o

Quake/cmd.i: Quake/cmd.c.i
.PHONY : Quake/cmd.i

# target to preprocess a source file
Quake/cmd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cmd.c.i
.PHONY : Quake/cmd.c.i

Quake/cmd.s: Quake/cmd.c.s
.PHONY : Quake/cmd.s

# target to generate assembly for a file
Quake/cmd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cmd.c.s
.PHONY : Quake/cmd.c.s

Quake/common.o: Quake/common.c.o
.PHONY : Quake/common.o

# target to build an object file
Quake/common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/common.c.o
.PHONY : Quake/common.c.o

Quake/common.i: Quake/common.c.i
.PHONY : Quake/common.i

# target to preprocess a source file
Quake/common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/common.c.i
.PHONY : Quake/common.c.i

Quake/common.s: Quake/common.c.s
.PHONY : Quake/common.s

# target to generate assembly for a file
Quake/common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/common.c.s
.PHONY : Quake/common.c.s

Quake/console.o: Quake/console.c.o
.PHONY : Quake/console.o

# target to build an object file
Quake/console.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/console.c.o
.PHONY : Quake/console.c.o

Quake/console.i: Quake/console.c.i
.PHONY : Quake/console.i

# target to preprocess a source file
Quake/console.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/console.c.i
.PHONY : Quake/console.c.i

Quake/console.s: Quake/console.c.s
.PHONY : Quake/console.s

# target to generate assembly for a file
Quake/console.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/console.c.s
.PHONY : Quake/console.c.s

Quake/crc.o: Quake/crc.c.o
.PHONY : Quake/crc.o

# target to build an object file
Quake/crc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/crc.c.o
.PHONY : Quake/crc.c.o

Quake/crc.i: Quake/crc.c.i
.PHONY : Quake/crc.i

# target to preprocess a source file
Quake/crc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/crc.c.i
.PHONY : Quake/crc.c.i

Quake/crc.s: Quake/crc.c.s
.PHONY : Quake/crc.s

# target to generate assembly for a file
Quake/crc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/crc.c.s
.PHONY : Quake/crc.c.s

Quake/cvar.o: Quake/cvar.c.o
.PHONY : Quake/cvar.o

# target to build an object file
Quake/cvar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cvar.c.o
.PHONY : Quake/cvar.c.o

Quake/cvar.i: Quake/cvar.c.i
.PHONY : Quake/cvar.i

# target to preprocess a source file
Quake/cvar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cvar.c.i
.PHONY : Quake/cvar.c.i

Quake/cvar.s: Quake/cvar.c.s
.PHONY : Quake/cvar.s

# target to generate assembly for a file
Quake/cvar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/cvar.c.s
.PHONY : Quake/cvar.c.s

Quake/fs_zip.o: Quake/fs_zip.c.o
.PHONY : Quake/fs_zip.o

# target to build an object file
Quake/fs_zip.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/fs_zip.c.o
.PHONY : Quake/fs_zip.c.o

Quake/fs_zip.i: Quake/fs_zip.c.i
.PHONY : Quake/fs_zip.i

# target to preprocess a source file
Quake/fs_zip.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/fs_zip.c.i
.PHONY : Quake/fs_zip.c.i

Quake/fs_zip.s: Quake/fs_zip.c.s
.PHONY : Quake/fs_zip.s

# target to generate assembly for a file
Quake/fs_zip.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/fs_zip.c.s
.PHONY : Quake/fs_zip.c.s

Quake/gl_draw.o: Quake/gl_draw.c.o
.PHONY : Quake/gl_draw.o

# target to build an object file
Quake/gl_draw.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_draw.c.o
.PHONY : Quake/gl_draw.c.o

Quake/gl_draw.i: Quake/gl_draw.c.i
.PHONY : Quake/gl_draw.i

# target to preprocess a source file
Quake/gl_draw.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_draw.c.i
.PHONY : Quake/gl_draw.c.i

Quake/gl_draw.s: Quake/gl_draw.c.s
.PHONY : Quake/gl_draw.s

# target to generate assembly for a file
Quake/gl_draw.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_draw.c.s
.PHONY : Quake/gl_draw.c.s

Quake/gl_fog.o: Quake/gl_fog.c.o
.PHONY : Quake/gl_fog.o

# target to build an object file
Quake/gl_fog.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_fog.c.o
.PHONY : Quake/gl_fog.c.o

Quake/gl_fog.i: Quake/gl_fog.c.i
.PHONY : Quake/gl_fog.i

# target to preprocess a source file
Quake/gl_fog.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_fog.c.i
.PHONY : Quake/gl_fog.c.i

Quake/gl_fog.s: Quake/gl_fog.c.s
.PHONY : Quake/gl_fog.s

# target to generate assembly for a file
Quake/gl_fog.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_fog.c.s
.PHONY : Quake/gl_fog.c.s

Quake/gl_mesh.o: Quake/gl_mesh.c.o
.PHONY : Quake/gl_mesh.o

# target to build an object file
Quake/gl_mesh.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_mesh.c.o
.PHONY : Quake/gl_mesh.c.o

Quake/gl_mesh.i: Quake/gl_mesh.c.i
.PHONY : Quake/gl_mesh.i

# target to preprocess a source file
Quake/gl_mesh.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_mesh.c.i
.PHONY : Quake/gl_mesh.c.i

Quake/gl_mesh.s: Quake/gl_mesh.c.s
.PHONY : Quake/gl_mesh.s

# target to generate assembly for a file
Quake/gl_mesh.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_mesh.c.s
.PHONY : Quake/gl_mesh.c.s

Quake/gl_model.o: Quake/gl_model.c.o
.PHONY : Quake/gl_model.o

# target to build an object file
Quake/gl_model.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_model.c.o
.PHONY : Quake/gl_model.c.o

Quake/gl_model.i: Quake/gl_model.c.i
.PHONY : Quake/gl_model.i

# target to preprocess a source file
Quake/gl_model.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_model.c.i
.PHONY : Quake/gl_model.c.i

Quake/gl_model.s: Quake/gl_model.c.s
.PHONY : Quake/gl_model.s

# target to generate assembly for a file
Quake/gl_model.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_model.c.s
.PHONY : Quake/gl_model.c.s

Quake/gl_refrag.o: Quake/gl_refrag.c.o
.PHONY : Quake/gl_refrag.o

# target to build an object file
Quake/gl_refrag.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_refrag.c.o
.PHONY : Quake/gl_refrag.c.o

Quake/gl_refrag.i: Quake/gl_refrag.c.i
.PHONY : Quake/gl_refrag.i

# target to preprocess a source file
Quake/gl_refrag.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_refrag.c.i
.PHONY : Quake/gl_refrag.c.i

Quake/gl_refrag.s: Quake/gl_refrag.c.s
.PHONY : Quake/gl_refrag.s

# target to generate assembly for a file
Quake/gl_refrag.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_refrag.c.s
.PHONY : Quake/gl_refrag.c.s

Quake/gl_rlight.o: Quake/gl_rlight.c.o
.PHONY : Quake/gl_rlight.o

# target to build an object file
Quake/gl_rlight.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_rlight.c.o
.PHONY : Quake/gl_rlight.c.o

Quake/gl_rlight.i: Quake/gl_rlight.c.i
.PHONY : Quake/gl_rlight.i

# target to preprocess a source file
Quake/gl_rlight.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_rlight.c.i
.PHONY : Quake/gl_rlight.c.i

Quake/gl_rlight.s: Quake/gl_rlight.c.s
.PHONY : Quake/gl_rlight.s

# target to generate assembly for a file
Quake/gl_rlight.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_rlight.c.s
.PHONY : Quake/gl_rlight.c.s

Quake/gl_rmain.o: Quake/gl_rmain.c.o
.PHONY : Quake/gl_rmain.o

# target to build an object file
Quake/gl_rmain.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_rmain.c.o
.PHONY : Quake/gl_rmain.c.o

Quake/gl_rmain.i: Quake/gl_rmain.c.i
.PHONY : Quake/gl_rmain.i

# target to preprocess a source file
Quake/gl_rmain.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_rmain.c.i
.PHONY : Quake/gl_rmain.c.i

Quake/gl_rmain.s: Quake/gl_rmain.c.s
.PHONY : Quake/gl_rmain.s

# target to generate assembly for a file
Quake/gl_rmain.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_rmain.c.s
.PHONY : Quake/gl_rmain.c.s

Quake/gl_rmisc.o: Quake/gl_rmisc.c.o
.PHONY : Quake/gl_rmisc.o

# target to build an object file
Quake/gl_rmisc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_rmisc.c.o
.PHONY : Quake/gl_rmisc.c.o

Quake/gl_rmisc.i: Quake/gl_rmisc.c.i
.PHONY : Quake/gl_rmisc.i

# target to preprocess a source file
Quake/gl_rmisc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_rmisc.c.i
.PHONY : Quake/gl_rmisc.c.i

Quake/gl_rmisc.s: Quake/gl_rmisc.c.s
.PHONY : Quake/gl_rmisc.s

# target to generate assembly for a file
Quake/gl_rmisc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_rmisc.c.s
.PHONY : Quake/gl_rmisc.c.s

Quake/gl_screen.o: Quake/gl_screen.c.o
.PHONY : Quake/gl_screen.o

# target to build an object file
Quake/gl_screen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_screen.c.o
.PHONY : Quake/gl_screen.c.o

Quake/gl_screen.i: Quake/gl_screen.c.i
.PHONY : Quake/gl_screen.i

# target to preprocess a source file
Quake/gl_screen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_screen.c.i
.PHONY : Quake/gl_screen.c.i

Quake/gl_screen.s: Quake/gl_screen.c.s
.PHONY : Quake/gl_screen.s

# target to generate assembly for a file
Quake/gl_screen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_screen.c.s
.PHONY : Quake/gl_screen.c.s

Quake/gl_sky.o: Quake/gl_sky.c.o
.PHONY : Quake/gl_sky.o

# target to build an object file
Quake/gl_sky.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_sky.c.o
.PHONY : Quake/gl_sky.c.o

Quake/gl_sky.i: Quake/gl_sky.c.i
.PHONY : Quake/gl_sky.i

# target to preprocess a source file
Quake/gl_sky.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_sky.c.i
.PHONY : Quake/gl_sky.c.i

Quake/gl_sky.s: Quake/gl_sky.c.s
.PHONY : Quake/gl_sky.s

# target to generate assembly for a file
Quake/gl_sky.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_sky.c.s
.PHONY : Quake/gl_sky.c.s

Quake/gl_texmgr.o: Quake/gl_texmgr.c.o
.PHONY : Quake/gl_texmgr.o

# target to build an object file
Quake/gl_texmgr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_texmgr.c.o
.PHONY : Quake/gl_texmgr.c.o

Quake/gl_texmgr.i: Quake/gl_texmgr.c.i
.PHONY : Quake/gl_texmgr.i

# target to preprocess a source file
Quake/gl_texmgr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_texmgr.c.i
.PHONY : Quake/gl_texmgr.c.i

Quake/gl_texmgr.s: Quake/gl_texmgr.c.s
.PHONY : Quake/gl_texmgr.s

# target to generate assembly for a file
Quake/gl_texmgr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_texmgr.c.s
.PHONY : Quake/gl_texmgr.c.s

Quake/gl_vidsdl.o: Quake/gl_vidsdl.c.o
.PHONY : Quake/gl_vidsdl.o

# target to build an object file
Quake/gl_vidsdl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_vidsdl.c.o
.PHONY : Quake/gl_vidsdl.c.o

Quake/gl_vidsdl.i: Quake/gl_vidsdl.c.i
.PHONY : Quake/gl_vidsdl.i

# target to preprocess a source file
Quake/gl_vidsdl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_vidsdl.c.i
.PHONY : Quake/gl_vidsdl.c.i

Quake/gl_vidsdl.s: Quake/gl_vidsdl.c.s
.PHONY : Quake/gl_vidsdl.s

# target to generate assembly for a file
Quake/gl_vidsdl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_vidsdl.c.s
.PHONY : Quake/gl_vidsdl.c.s

Quake/gl_warp.o: Quake/gl_warp.c.o
.PHONY : Quake/gl_warp.o

# target to build an object file
Quake/gl_warp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_warp.c.o
.PHONY : Quake/gl_warp.c.o

Quake/gl_warp.i: Quake/gl_warp.c.i
.PHONY : Quake/gl_warp.i

# target to preprocess a source file
Quake/gl_warp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_warp.c.i
.PHONY : Quake/gl_warp.c.i

Quake/gl_warp.s: Quake/gl_warp.c.s
.PHONY : Quake/gl_warp.s

# target to generate assembly for a file
Quake/gl_warp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/gl_warp.c.s
.PHONY : Quake/gl_warp.c.s

Quake/host.o: Quake/host.c.o
.PHONY : Quake/host.o

# target to build an object file
Quake/host.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/host.c.o
.PHONY : Quake/host.c.o

Quake/host.i: Quake/host.c.i
.PHONY : Quake/host.i

# target to preprocess a source file
Quake/host.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/host.c.i
.PHONY : Quake/host.c.i

Quake/host.s: Quake/host.c.s
.PHONY : Quake/host.s

# target to generate assembly for a file
Quake/host.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/host.c.s
.PHONY : Quake/host.c.s

Quake/host_cmd.o: Quake/host_cmd.c.o
.PHONY : Quake/host_cmd.o

# target to build an object file
Quake/host_cmd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/host_cmd.c.o
.PHONY : Quake/host_cmd.c.o

Quake/host_cmd.i: Quake/host_cmd.c.i
.PHONY : Quake/host_cmd.i

# target to preprocess a source file
Quake/host_cmd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/host_cmd.c.i
.PHONY : Quake/host_cmd.c.i

Quake/host_cmd.s: Quake/host_cmd.c.s
.PHONY : Quake/host_cmd.s

# target to generate assembly for a file
Quake/host_cmd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/host_cmd.c.s
.PHONY : Quake/host_cmd.c.s

Quake/image.o: Quake/image.c.o
.PHONY : Quake/image.o

# target to build an object file
Quake/image.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/image.c.o
.PHONY : Quake/image.c.o

Quake/image.i: Quake/image.c.i
.PHONY : Quake/image.i

# target to preprocess a source file
Quake/image.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/image.c.i
.PHONY : Quake/image.c.i

Quake/image.s: Quake/image.c.s
.PHONY : Quake/image.s

# target to generate assembly for a file
Quake/image.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/image.c.s
.PHONY : Quake/image.c.s

Quake/in_sdl.o: Quake/in_sdl.c.o
.PHONY : Quake/in_sdl.o

# target to build an object file
Quake/in_sdl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/in_sdl.c.o
.PHONY : Quake/in_sdl.c.o

Quake/in_sdl.i: Quake/in_sdl.c.i
.PHONY : Quake/in_sdl.i

# target to preprocess a source file
Quake/in_sdl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/in_sdl.c.i
.PHONY : Quake/in_sdl.c.i

Quake/in_sdl.s: Quake/in_sdl.c.s
.PHONY : Quake/in_sdl.s

# target to generate assembly for a file
Quake/in_sdl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/in_sdl.c.s
.PHONY : Quake/in_sdl.c.s

Quake/keys.o: Quake/keys.c.o
.PHONY : Quake/keys.o

# target to build an object file
Quake/keys.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/keys.c.o
.PHONY : Quake/keys.c.o

Quake/keys.i: Quake/keys.c.i
.PHONY : Quake/keys.i

# target to preprocess a source file
Quake/keys.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/keys.c.i
.PHONY : Quake/keys.c.i

Quake/keys.s: Quake/keys.c.s
.PHONY : Quake/keys.s

# target to generate assembly for a file
Quake/keys.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/keys.c.s
.PHONY : Quake/keys.c.s

Quake/main_sdl.o: Quake/main_sdl.c.o
.PHONY : Quake/main_sdl.o

# target to build an object file
Quake/main_sdl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/main_sdl.c.o
.PHONY : Quake/main_sdl.c.o

Quake/main_sdl.i: Quake/main_sdl.c.i
.PHONY : Quake/main_sdl.i

# target to preprocess a source file
Quake/main_sdl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/main_sdl.c.i
.PHONY : Quake/main_sdl.c.i

Quake/main_sdl.s: Quake/main_sdl.c.s
.PHONY : Quake/main_sdl.s

# target to generate assembly for a file
Quake/main_sdl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/main_sdl.c.s
.PHONY : Quake/main_sdl.c.s

Quake/mathlib.o: Quake/mathlib.c.o
.PHONY : Quake/mathlib.o

# target to build an object file
Quake/mathlib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/mathlib.c.o
.PHONY : Quake/mathlib.c.o

Quake/mathlib.i: Quake/mathlib.c.i
.PHONY : Quake/mathlib.i

# target to preprocess a source file
Quake/mathlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/mathlib.c.i
.PHONY : Quake/mathlib.c.i

Quake/mathlib.s: Quake/mathlib.c.s
.PHONY : Quake/mathlib.s

# target to generate assembly for a file
Quake/mathlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/mathlib.c.s
.PHONY : Quake/mathlib.c.s

Quake/mdfour.o: Quake/mdfour.c.o
.PHONY : Quake/mdfour.o

# target to build an object file
Quake/mdfour.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/mdfour.c.o
.PHONY : Quake/mdfour.c.o

Quake/mdfour.i: Quake/mdfour.c.i
.PHONY : Quake/mdfour.i

# target to preprocess a source file
Quake/mdfour.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/mdfour.c.i
.PHONY : Quake/mdfour.c.i

Quake/mdfour.s: Quake/mdfour.c.s
.PHONY : Quake/mdfour.s

# target to generate assembly for a file
Quake/mdfour.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/mdfour.c.s
.PHONY : Quake/mdfour.c.s

Quake/menu.o: Quake/menu.c.o
.PHONY : Quake/menu.o

# target to build an object file
Quake/menu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/menu.c.o
.PHONY : Quake/menu.c.o

Quake/menu.i: Quake/menu.c.i
.PHONY : Quake/menu.i

# target to preprocess a source file
Quake/menu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/menu.c.i
.PHONY : Quake/menu.c.i

Quake/menu.s: Quake/menu.c.s
.PHONY : Quake/menu.s

# target to generate assembly for a file
Quake/menu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/menu.c.s
.PHONY : Quake/menu.c.s

Quake/net_bsd.o: Quake/net_bsd.c.o
.PHONY : Quake/net_bsd.o

# target to build an object file
Quake/net_bsd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/net_bsd.c.o
.PHONY : Quake/net_bsd.c.o

Quake/net_bsd.i: Quake/net_bsd.c.i
.PHONY : Quake/net_bsd.i

# target to preprocess a source file
Quake/net_bsd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/net_bsd.c.i
.PHONY : Quake/net_bsd.c.i

Quake/net_bsd.s: Quake/net_bsd.c.s
.PHONY : Quake/net_bsd.s

# target to generate assembly for a file
Quake/net_bsd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/net_bsd.c.s
.PHONY : Quake/net_bsd.c.s

Quake/net_dgrm.o: Quake/net_dgrm.c.o
.PHONY : Quake/net_dgrm.o

# target to build an object file
Quake/net_dgrm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/net_dgrm.c.o
.PHONY : Quake/net_dgrm.c.o

Quake/net_dgrm.i: Quake/net_dgrm.c.i
.PHONY : Quake/net_dgrm.i

# target to preprocess a source file
Quake/net_dgrm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/net_dgrm.c.i
.PHONY : Quake/net_dgrm.c.i

Quake/net_dgrm.s: Quake/net_dgrm.c.s
.PHONY : Quake/net_dgrm.s

# target to generate assembly for a file
Quake/net_dgrm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/net_dgrm.c.s
.PHONY : Quake/net_dgrm.c.s

Quake/net_loop.o: Quake/net_loop.c.o
.PHONY : Quake/net_loop.o

# target to build an object file
Quake/net_loop.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/net_loop.c.o
.PHONY : Quake/net_loop.c.o

Quake/net_loop.i: Quake/net_loop.c.i
.PHONY : Quake/net_loop.i

# target to preprocess a source file
Quake/net_loop.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/net_loop.c.i
.PHONY : Quake/net_loop.c.i

Quake/net_loop.s: Quake/net_loop.c.s
.PHONY : Quake/net_loop.s

# target to generate assembly for a file
Quake/net_loop.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/net_loop.c.s
.PHONY : Quake/net_loop.c.s

Quake/net_main.o: Quake/net_main.c.o
.PHONY : Quake/net_main.o

# target to build an object file
Quake/net_main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/net_main.c.o
.PHONY : Quake/net_main.c.o

Quake/net_main.i: Quake/net_main.c.i
.PHONY : Quake/net_main.i

# target to preprocess a source file
Quake/net_main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/net_main.c.i
.PHONY : Quake/net_main.c.i

Quake/net_main.s: Quake/net_main.c.s
.PHONY : Quake/net_main.s

# target to generate assembly for a file
Quake/net_main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/net_main.c.s
.PHONY : Quake/net_main.c.s

Quake/net_udp.o: Quake/net_udp.c.o
.PHONY : Quake/net_udp.o

# target to build an object file
Quake/net_udp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/net_udp.c.o
.PHONY : Quake/net_udp.c.o

Quake/net_udp.i: Quake/net_udp.c.i
.PHONY : Quake/net_udp.i

# target to preprocess a source file
Quake/net_udp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/net_udp.c.i
.PHONY : Quake/net_udp.c.i

Quake/net_udp.s: Quake/net_udp.c.s
.PHONY : Quake/net_udp.s

# target to generate assembly for a file
Quake/net_udp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/net_udp.c.s
.PHONY : Quake/net_udp.c.s

Quake/pl_linux.o: Quake/pl_linux.c.o
.PHONY : Quake/pl_linux.o

# target to build an object file
Quake/pl_linux.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pl_linux.c.o
.PHONY : Quake/pl_linux.c.o

Quake/pl_linux.i: Quake/pl_linux.c.i
.PHONY : Quake/pl_linux.i

# target to preprocess a source file
Quake/pl_linux.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pl_linux.c.i
.PHONY : Quake/pl_linux.c.i

Quake/pl_linux.s: Quake/pl_linux.c.s
.PHONY : Quake/pl_linux.s

# target to generate assembly for a file
Quake/pl_linux.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pl_linux.c.s
.PHONY : Quake/pl_linux.c.s

Quake/pmove.o: Quake/pmove.c.o
.PHONY : Quake/pmove.o

# target to build an object file
Quake/pmove.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pmove.c.o
.PHONY : Quake/pmove.c.o

Quake/pmove.i: Quake/pmove.c.i
.PHONY : Quake/pmove.i

# target to preprocess a source file
Quake/pmove.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pmove.c.i
.PHONY : Quake/pmove.c.i

Quake/pmove.s: Quake/pmove.c.s
.PHONY : Quake/pmove.s

# target to generate assembly for a file
Quake/pmove.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pmove.c.s
.PHONY : Quake/pmove.c.s

Quake/pmovetst.o: Quake/pmovetst.c.o
.PHONY : Quake/pmovetst.o

# target to build an object file
Quake/pmovetst.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pmovetst.c.o
.PHONY : Quake/pmovetst.c.o

Quake/pmovetst.i: Quake/pmovetst.c.i
.PHONY : Quake/pmovetst.i

# target to preprocess a source file
Quake/pmovetst.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pmovetst.c.i
.PHONY : Quake/pmovetst.c.i

Quake/pmovetst.s: Quake/pmovetst.c.s
.PHONY : Quake/pmovetst.s

# target to generate assembly for a file
Quake/pmovetst.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pmovetst.c.s
.PHONY : Quake/pmovetst.c.s

Quake/pr_cmds.o: Quake/pr_cmds.c.o
.PHONY : Quake/pr_cmds.o

# target to build an object file
Quake/pr_cmds.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pr_cmds.c.o
.PHONY : Quake/pr_cmds.c.o

Quake/pr_cmds.i: Quake/pr_cmds.c.i
.PHONY : Quake/pr_cmds.i

# target to preprocess a source file
Quake/pr_cmds.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pr_cmds.c.i
.PHONY : Quake/pr_cmds.c.i

Quake/pr_cmds.s: Quake/pr_cmds.c.s
.PHONY : Quake/pr_cmds.s

# target to generate assembly for a file
Quake/pr_cmds.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pr_cmds.c.s
.PHONY : Quake/pr_cmds.c.s

Quake/pr_edict.o: Quake/pr_edict.c.o
.PHONY : Quake/pr_edict.o

# target to build an object file
Quake/pr_edict.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pr_edict.c.o
.PHONY : Quake/pr_edict.c.o

Quake/pr_edict.i: Quake/pr_edict.c.i
.PHONY : Quake/pr_edict.i

# target to preprocess a source file
Quake/pr_edict.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pr_edict.c.i
.PHONY : Quake/pr_edict.c.i

Quake/pr_edict.s: Quake/pr_edict.c.s
.PHONY : Quake/pr_edict.s

# target to generate assembly for a file
Quake/pr_edict.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pr_edict.c.s
.PHONY : Quake/pr_edict.c.s

Quake/pr_exec.o: Quake/pr_exec.c.o
.PHONY : Quake/pr_exec.o

# target to build an object file
Quake/pr_exec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pr_exec.c.o
.PHONY : Quake/pr_exec.c.o

Quake/pr_exec.i: Quake/pr_exec.c.i
.PHONY : Quake/pr_exec.i

# target to preprocess a source file
Quake/pr_exec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pr_exec.c.i
.PHONY : Quake/pr_exec.c.i

Quake/pr_exec.s: Quake/pr_exec.c.s
.PHONY : Quake/pr_exec.s

# target to generate assembly for a file
Quake/pr_exec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pr_exec.c.s
.PHONY : Quake/pr_exec.c.s

Quake/pr_ext.o: Quake/pr_ext.c.o
.PHONY : Quake/pr_ext.o

# target to build an object file
Quake/pr_ext.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pr_ext.c.o
.PHONY : Quake/pr_ext.c.o

Quake/pr_ext.i: Quake/pr_ext.c.i
.PHONY : Quake/pr_ext.i

# target to preprocess a source file
Quake/pr_ext.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pr_ext.c.i
.PHONY : Quake/pr_ext.c.i

Quake/pr_ext.s: Quake/pr_ext.c.s
.PHONY : Quake/pr_ext.s

# target to generate assembly for a file
Quake/pr_ext.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/pr_ext.c.s
.PHONY : Quake/pr_ext.c.s

Quake/r_alias.o: Quake/r_alias.c.o
.PHONY : Quake/r_alias.o

# target to build an object file
Quake/r_alias.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/r_alias.c.o
.PHONY : Quake/r_alias.c.o

Quake/r_alias.i: Quake/r_alias.c.i
.PHONY : Quake/r_alias.i

# target to preprocess a source file
Quake/r_alias.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/r_alias.c.i
.PHONY : Quake/r_alias.c.i

Quake/r_alias.s: Quake/r_alias.c.s
.PHONY : Quake/r_alias.s

# target to generate assembly for a file
Quake/r_alias.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/r_alias.c.s
.PHONY : Quake/r_alias.c.s

Quake/r_brush.o: Quake/r_brush.c.o
.PHONY : Quake/r_brush.o

# target to build an object file
Quake/r_brush.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/r_brush.c.o
.PHONY : Quake/r_brush.c.o

Quake/r_brush.i: Quake/r_brush.c.i
.PHONY : Quake/r_brush.i

# target to preprocess a source file
Quake/r_brush.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/r_brush.c.i
.PHONY : Quake/r_brush.c.i

Quake/r_brush.s: Quake/r_brush.c.s
.PHONY : Quake/r_brush.s

# target to generate assembly for a file
Quake/r_brush.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/r_brush.c.s
.PHONY : Quake/r_brush.c.s

Quake/r_part.o: Quake/r_part.c.o
.PHONY : Quake/r_part.o

# target to build an object file
Quake/r_part.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/r_part.c.o
.PHONY : Quake/r_part.c.o

Quake/r_part.i: Quake/r_part.c.i
.PHONY : Quake/r_part.i

# target to preprocess a source file
Quake/r_part.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/r_part.c.i
.PHONY : Quake/r_part.c.i

Quake/r_part.s: Quake/r_part.c.s
.PHONY : Quake/r_part.s

# target to generate assembly for a file
Quake/r_part.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/r_part.c.s
.PHONY : Quake/r_part.c.s

Quake/r_part_fte.o: Quake/r_part_fte.c.o
.PHONY : Quake/r_part_fte.o

# target to build an object file
Quake/r_part_fte.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/r_part_fte.c.o
.PHONY : Quake/r_part_fte.c.o

Quake/r_part_fte.i: Quake/r_part_fte.c.i
.PHONY : Quake/r_part_fte.i

# target to preprocess a source file
Quake/r_part_fte.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/r_part_fte.c.i
.PHONY : Quake/r_part_fte.c.i

Quake/r_part_fte.s: Quake/r_part_fte.c.s
.PHONY : Quake/r_part_fte.s

# target to generate assembly for a file
Quake/r_part_fte.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/r_part_fte.c.s
.PHONY : Quake/r_part_fte.c.s

Quake/r_sprite.o: Quake/r_sprite.c.o
.PHONY : Quake/r_sprite.o

# target to build an object file
Quake/r_sprite.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/r_sprite.c.o
.PHONY : Quake/r_sprite.c.o

Quake/r_sprite.i: Quake/r_sprite.c.i
.PHONY : Quake/r_sprite.i

# target to preprocess a source file
Quake/r_sprite.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/r_sprite.c.i
.PHONY : Quake/r_sprite.c.i

Quake/r_sprite.s: Quake/r_sprite.c.s
.PHONY : Quake/r_sprite.s

# target to generate assembly for a file
Quake/r_sprite.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/r_sprite.c.s
.PHONY : Quake/r_sprite.c.s

Quake/r_world.o: Quake/r_world.c.o
.PHONY : Quake/r_world.o

# target to build an object file
Quake/r_world.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/r_world.c.o
.PHONY : Quake/r_world.c.o

Quake/r_world.i: Quake/r_world.c.i
.PHONY : Quake/r_world.i

# target to preprocess a source file
Quake/r_world.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/r_world.c.i
.PHONY : Quake/r_world.c.i

Quake/r_world.s: Quake/r_world.c.s
.PHONY : Quake/r_world.s

# target to generate assembly for a file
Quake/r_world.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/r_world.c.s
.PHONY : Quake/r_world.c.s

Quake/sbar.o: Quake/sbar.c.o
.PHONY : Quake/sbar.o

# target to build an object file
Quake/sbar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/sbar.c.o
.PHONY : Quake/sbar.c.o

Quake/sbar.i: Quake/sbar.c.i
.PHONY : Quake/sbar.i

# target to preprocess a source file
Quake/sbar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/sbar.c.i
.PHONY : Quake/sbar.c.i

Quake/sbar.s: Quake/sbar.c.s
.PHONY : Quake/sbar.s

# target to generate assembly for a file
Quake/sbar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/sbar.c.s
.PHONY : Quake/sbar.c.s

Quake/snd_codec.o: Quake/snd_codec.c.o
.PHONY : Quake/snd_codec.o

# target to build an object file
Quake/snd_codec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_codec.c.o
.PHONY : Quake/snd_codec.c.o

Quake/snd_codec.i: Quake/snd_codec.c.i
.PHONY : Quake/snd_codec.i

# target to preprocess a source file
Quake/snd_codec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_codec.c.i
.PHONY : Quake/snd_codec.c.i

Quake/snd_codec.s: Quake/snd_codec.c.s
.PHONY : Quake/snd_codec.s

# target to generate assembly for a file
Quake/snd_codec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_codec.c.s
.PHONY : Quake/snd_codec.c.s

Quake/snd_dma.o: Quake/snd_dma.c.o
.PHONY : Quake/snd_dma.o

# target to build an object file
Quake/snd_dma.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_dma.c.o
.PHONY : Quake/snd_dma.c.o

Quake/snd_dma.i: Quake/snd_dma.c.i
.PHONY : Quake/snd_dma.i

# target to preprocess a source file
Quake/snd_dma.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_dma.c.i
.PHONY : Quake/snd_dma.c.i

Quake/snd_dma.s: Quake/snd_dma.c.s
.PHONY : Quake/snd_dma.s

# target to generate assembly for a file
Quake/snd_dma.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_dma.c.s
.PHONY : Quake/snd_dma.c.s

Quake/snd_mem.o: Quake/snd_mem.c.o
.PHONY : Quake/snd_mem.o

# target to build an object file
Quake/snd_mem.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_mem.c.o
.PHONY : Quake/snd_mem.c.o

Quake/snd_mem.i: Quake/snd_mem.c.i
.PHONY : Quake/snd_mem.i

# target to preprocess a source file
Quake/snd_mem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_mem.c.i
.PHONY : Quake/snd_mem.c.i

Quake/snd_mem.s: Quake/snd_mem.c.s
.PHONY : Quake/snd_mem.s

# target to generate assembly for a file
Quake/snd_mem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_mem.c.s
.PHONY : Quake/snd_mem.c.s

Quake/snd_mix.o: Quake/snd_mix.c.o
.PHONY : Quake/snd_mix.o

# target to build an object file
Quake/snd_mix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_mix.c.o
.PHONY : Quake/snd_mix.c.o

Quake/snd_mix.i: Quake/snd_mix.c.i
.PHONY : Quake/snd_mix.i

# target to preprocess a source file
Quake/snd_mix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_mix.c.i
.PHONY : Quake/snd_mix.c.i

Quake/snd_mix.s: Quake/snd_mix.c.s
.PHONY : Quake/snd_mix.s

# target to generate assembly for a file
Quake/snd_mix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_mix.c.s
.PHONY : Quake/snd_mix.c.s

Quake/snd_mp3tag.o: Quake/snd_mp3tag.c.o
.PHONY : Quake/snd_mp3tag.o

# target to build an object file
Quake/snd_mp3tag.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_mp3tag.c.o
.PHONY : Quake/snd_mp3tag.c.o

Quake/snd_mp3tag.i: Quake/snd_mp3tag.c.i
.PHONY : Quake/snd_mp3tag.i

# target to preprocess a source file
Quake/snd_mp3tag.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_mp3tag.c.i
.PHONY : Quake/snd_mp3tag.c.i

Quake/snd_mp3tag.s: Quake/snd_mp3tag.c.s
.PHONY : Quake/snd_mp3tag.s

# target to generate assembly for a file
Quake/snd_mp3tag.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_mp3tag.c.s
.PHONY : Quake/snd_mp3tag.c.s

Quake/snd_sdl.o: Quake/snd_sdl.c.o
.PHONY : Quake/snd_sdl.o

# target to build an object file
Quake/snd_sdl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_sdl.c.o
.PHONY : Quake/snd_sdl.c.o

Quake/snd_sdl.i: Quake/snd_sdl.c.i
.PHONY : Quake/snd_sdl.i

# target to preprocess a source file
Quake/snd_sdl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_sdl.c.i
.PHONY : Quake/snd_sdl.c.i

Quake/snd_sdl.s: Quake/snd_sdl.c.s
.PHONY : Quake/snd_sdl.s

# target to generate assembly for a file
Quake/snd_sdl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_sdl.c.s
.PHONY : Quake/snd_sdl.c.s

Quake/snd_voip.o: Quake/snd_voip.c.o
.PHONY : Quake/snd_voip.o

# target to build an object file
Quake/snd_voip.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_voip.c.o
.PHONY : Quake/snd_voip.c.o

Quake/snd_voip.i: Quake/snd_voip.c.i
.PHONY : Quake/snd_voip.i

# target to preprocess a source file
Quake/snd_voip.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_voip.c.i
.PHONY : Quake/snd_voip.c.i

Quake/snd_voip.s: Quake/snd_voip.c.s
.PHONY : Quake/snd_voip.s

# target to generate assembly for a file
Quake/snd_voip.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_voip.c.s
.PHONY : Quake/snd_voip.c.s

Quake/snd_wave.o: Quake/snd_wave.c.o
.PHONY : Quake/snd_wave.o

# target to build an object file
Quake/snd_wave.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_wave.c.o
.PHONY : Quake/snd_wave.c.o

Quake/snd_wave.i: Quake/snd_wave.c.i
.PHONY : Quake/snd_wave.i

# target to preprocess a source file
Quake/snd_wave.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_wave.c.i
.PHONY : Quake/snd_wave.c.i

Quake/snd_wave.s: Quake/snd_wave.c.s
.PHONY : Quake/snd_wave.s

# target to generate assembly for a file
Quake/snd_wave.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/snd_wave.c.s
.PHONY : Quake/snd_wave.c.s

Quake/strlcat.o: Quake/strlcat.c.o
.PHONY : Quake/strlcat.o

# target to build an object file
Quake/strlcat.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/strlcat.c.o
.PHONY : Quake/strlcat.c.o

Quake/strlcat.i: Quake/strlcat.c.i
.PHONY : Quake/strlcat.i

# target to preprocess a source file
Quake/strlcat.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/strlcat.c.i
.PHONY : Quake/strlcat.c.i

Quake/strlcat.s: Quake/strlcat.c.s
.PHONY : Quake/strlcat.s

# target to generate assembly for a file
Quake/strlcat.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/strlcat.c.s
.PHONY : Quake/strlcat.c.s

Quake/strlcpy.o: Quake/strlcpy.c.o
.PHONY : Quake/strlcpy.o

# target to build an object file
Quake/strlcpy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/strlcpy.c.o
.PHONY : Quake/strlcpy.c.o

Quake/strlcpy.i: Quake/strlcpy.c.i
.PHONY : Quake/strlcpy.i

# target to preprocess a source file
Quake/strlcpy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/strlcpy.c.i
.PHONY : Quake/strlcpy.c.i

Quake/strlcpy.s: Quake/strlcpy.c.s
.PHONY : Quake/strlcpy.s

# target to generate assembly for a file
Quake/strlcpy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/strlcpy.c.s
.PHONY : Quake/strlcpy.c.s

Quake/sv_main.o: Quake/sv_main.c.o
.PHONY : Quake/sv_main.o

# target to build an object file
Quake/sv_main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/sv_main.c.o
.PHONY : Quake/sv_main.c.o

Quake/sv_main.i: Quake/sv_main.c.i
.PHONY : Quake/sv_main.i

# target to preprocess a source file
Quake/sv_main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/sv_main.c.i
.PHONY : Quake/sv_main.c.i

Quake/sv_main.s: Quake/sv_main.c.s
.PHONY : Quake/sv_main.s

# target to generate assembly for a file
Quake/sv_main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/sv_main.c.s
.PHONY : Quake/sv_main.c.s

Quake/sv_move.o: Quake/sv_move.c.o
.PHONY : Quake/sv_move.o

# target to build an object file
Quake/sv_move.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/sv_move.c.o
.PHONY : Quake/sv_move.c.o

Quake/sv_move.i: Quake/sv_move.c.i
.PHONY : Quake/sv_move.i

# target to preprocess a source file
Quake/sv_move.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/sv_move.c.i
.PHONY : Quake/sv_move.c.i

Quake/sv_move.s: Quake/sv_move.c.s
.PHONY : Quake/sv_move.s

# target to generate assembly for a file
Quake/sv_move.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/sv_move.c.s
.PHONY : Quake/sv_move.c.s

Quake/sv_phys.o: Quake/sv_phys.c.o
.PHONY : Quake/sv_phys.o

# target to build an object file
Quake/sv_phys.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/sv_phys.c.o
.PHONY : Quake/sv_phys.c.o

Quake/sv_phys.i: Quake/sv_phys.c.i
.PHONY : Quake/sv_phys.i

# target to preprocess a source file
Quake/sv_phys.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/sv_phys.c.i
.PHONY : Quake/sv_phys.c.i

Quake/sv_phys.s: Quake/sv_phys.c.s
.PHONY : Quake/sv_phys.s

# target to generate assembly for a file
Quake/sv_phys.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/sv_phys.c.s
.PHONY : Quake/sv_phys.c.s

Quake/sv_user.o: Quake/sv_user.c.o
.PHONY : Quake/sv_user.o

# target to build an object file
Quake/sv_user.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/sv_user.c.o
.PHONY : Quake/sv_user.c.o

Quake/sv_user.i: Quake/sv_user.c.i
.PHONY : Quake/sv_user.i

# target to preprocess a source file
Quake/sv_user.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/sv_user.c.i
.PHONY : Quake/sv_user.c.i

Quake/sv_user.s: Quake/sv_user.c.s
.PHONY : Quake/sv_user.s

# target to generate assembly for a file
Quake/sv_user.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/sv_user.c.s
.PHONY : Quake/sv_user.c.s

Quake/sys_sdl_unix.o: Quake/sys_sdl_unix.c.o
.PHONY : Quake/sys_sdl_unix.o

# target to build an object file
Quake/sys_sdl_unix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/sys_sdl_unix.c.o
.PHONY : Quake/sys_sdl_unix.c.o

Quake/sys_sdl_unix.i: Quake/sys_sdl_unix.c.i
.PHONY : Quake/sys_sdl_unix.i

# target to preprocess a source file
Quake/sys_sdl_unix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/sys_sdl_unix.c.i
.PHONY : Quake/sys_sdl_unix.c.i

Quake/sys_sdl_unix.s: Quake/sys_sdl_unix.c.s
.PHONY : Quake/sys_sdl_unix.s

# target to generate assembly for a file
Quake/sys_sdl_unix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/sys_sdl_unix.c.s
.PHONY : Quake/sys_sdl_unix.c.s

Quake/view.o: Quake/view.c.o
.PHONY : Quake/view.o

# target to build an object file
Quake/view.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/view.c.o
.PHONY : Quake/view.c.o

Quake/view.i: Quake/view.c.i
.PHONY : Quake/view.i

# target to preprocess a source file
Quake/view.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/view.c.i
.PHONY : Quake/view.c.i

Quake/view.s: Quake/view.c.s
.PHONY : Quake/view.s

# target to generate assembly for a file
Quake/view.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/view.c.s
.PHONY : Quake/view.c.s

Quake/wad.o: Quake/wad.c.o
.PHONY : Quake/wad.o

# target to build an object file
Quake/wad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/wad.c.o
.PHONY : Quake/wad.c.o

Quake/wad.i: Quake/wad.c.i
.PHONY : Quake/wad.i

# target to preprocess a source file
Quake/wad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/wad.c.i
.PHONY : Quake/wad.c.i

Quake/wad.s: Quake/wad.c.s
.PHONY : Quake/wad.s

# target to generate assembly for a file
Quake/wad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/wad.c.s
.PHONY : Quake/wad.c.s

Quake/world.o: Quake/world.c.o
.PHONY : Quake/world.o

# target to build an object file
Quake/world.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/world.c.o
.PHONY : Quake/world.c.o

Quake/world.i: Quake/world.c.i
.PHONY : Quake/world.i

# target to preprocess a source file
Quake/world.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/world.c.i
.PHONY : Quake/world.c.i

Quake/world.s: Quake/world.c.s
.PHONY : Quake/world.s

# target to generate assembly for a file
Quake/world.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/world.c.s
.PHONY : Quake/world.c.s

Quake/zone.o: Quake/zone.c.o
.PHONY : Quake/zone.o

# target to build an object file
Quake/zone.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/zone.c.o
.PHONY : Quake/zone.c.o

Quake/zone.i: Quake/zone.c.i
.PHONY : Quake/zone.i

# target to preprocess a source file
Quake/zone.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/zone.c.i
.PHONY : Quake/zone.c.i

Quake/zone.s: Quake/zone.c.s
.PHONY : Quake/zone.s

# target to generate assembly for a file
Quake/zone.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakespasm.dir/build.make CMakeFiles/quakespasm.dir/Quake/zone.c.s
.PHONY : Quake/zone.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... quakespasm"
	@echo "... Quake/bgmusic.o"
	@echo "... Quake/bgmusic.i"
	@echo "... Quake/bgmusic.s"
	@echo "... Quake/cd_sdl.o"
	@echo "... Quake/cd_sdl.i"
	@echo "... Quake/cd_sdl.s"
	@echo "... Quake/cfgfile.o"
	@echo "... Quake/cfgfile.i"
	@echo "... Quake/cfgfile.s"
	@echo "... Quake/chase.o"
	@echo "... Quake/chase.i"
	@echo "... Quake/chase.s"
	@echo "... Quake/cl_demo.o"
	@echo "... Quake/cl_demo.i"
	@echo "... Quake/cl_demo.s"
	@echo "... Quake/cl_input.o"
	@echo "... Quake/cl_input.i"
	@echo "... Quake/cl_input.s"
	@echo "... Quake/cl_main.o"
	@echo "... Quake/cl_main.i"
	@echo "... Quake/cl_main.s"
	@echo "... Quake/cl_parse.o"
	@echo "... Quake/cl_parse.i"
	@echo "... Quake/cl_parse.s"
	@echo "... Quake/cl_tent.o"
	@echo "... Quake/cl_tent.i"
	@echo "... Quake/cl_tent.s"
	@echo "... Quake/cmd.o"
	@echo "... Quake/cmd.i"
	@echo "... Quake/cmd.s"
	@echo "... Quake/common.o"
	@echo "... Quake/common.i"
	@echo "... Quake/common.s"
	@echo "... Quake/console.o"
	@echo "... Quake/console.i"
	@echo "... Quake/console.s"
	@echo "... Quake/crc.o"
	@echo "... Quake/crc.i"
	@echo "... Quake/crc.s"
	@echo "... Quake/cvar.o"
	@echo "... Quake/cvar.i"
	@echo "... Quake/cvar.s"
	@echo "... Quake/fs_zip.o"
	@echo "... Quake/fs_zip.i"
	@echo "... Quake/fs_zip.s"
	@echo "... Quake/gl_draw.o"
	@echo "... Quake/gl_draw.i"
	@echo "... Quake/gl_draw.s"
	@echo "... Quake/gl_fog.o"
	@echo "... Quake/gl_fog.i"
	@echo "... Quake/gl_fog.s"
	@echo "... Quake/gl_mesh.o"
	@echo "... Quake/gl_mesh.i"
	@echo "... Quake/gl_mesh.s"
	@echo "... Quake/gl_model.o"
	@echo "... Quake/gl_model.i"
	@echo "... Quake/gl_model.s"
	@echo "... Quake/gl_refrag.o"
	@echo "... Quake/gl_refrag.i"
	@echo "... Quake/gl_refrag.s"
	@echo "... Quake/gl_rlight.o"
	@echo "... Quake/gl_rlight.i"
	@echo "... Quake/gl_rlight.s"
	@echo "... Quake/gl_rmain.o"
	@echo "... Quake/gl_rmain.i"
	@echo "... Quake/gl_rmain.s"
	@echo "... Quake/gl_rmisc.o"
	@echo "... Quake/gl_rmisc.i"
	@echo "... Quake/gl_rmisc.s"
	@echo "... Quake/gl_screen.o"
	@echo "... Quake/gl_screen.i"
	@echo "... Quake/gl_screen.s"
	@echo "... Quake/gl_sky.o"
	@echo "... Quake/gl_sky.i"
	@echo "... Quake/gl_sky.s"
	@echo "... Quake/gl_texmgr.o"
	@echo "... Quake/gl_texmgr.i"
	@echo "... Quake/gl_texmgr.s"
	@echo "... Quake/gl_vidsdl.o"
	@echo "... Quake/gl_vidsdl.i"
	@echo "... Quake/gl_vidsdl.s"
	@echo "... Quake/gl_warp.o"
	@echo "... Quake/gl_warp.i"
	@echo "... Quake/gl_warp.s"
	@echo "... Quake/host.o"
	@echo "... Quake/host.i"
	@echo "... Quake/host.s"
	@echo "... Quake/host_cmd.o"
	@echo "... Quake/host_cmd.i"
	@echo "... Quake/host_cmd.s"
	@echo "... Quake/image.o"
	@echo "... Quake/image.i"
	@echo "... Quake/image.s"
	@echo "... Quake/in_sdl.o"
	@echo "... Quake/in_sdl.i"
	@echo "... Quake/in_sdl.s"
	@echo "... Quake/keys.o"
	@echo "... Quake/keys.i"
	@echo "... Quake/keys.s"
	@echo "... Quake/main_sdl.o"
	@echo "... Quake/main_sdl.i"
	@echo "... Quake/main_sdl.s"
	@echo "... Quake/mathlib.o"
	@echo "... Quake/mathlib.i"
	@echo "... Quake/mathlib.s"
	@echo "... Quake/mdfour.o"
	@echo "... Quake/mdfour.i"
	@echo "... Quake/mdfour.s"
	@echo "... Quake/menu.o"
	@echo "... Quake/menu.i"
	@echo "... Quake/menu.s"
	@echo "... Quake/net_bsd.o"
	@echo "... Quake/net_bsd.i"
	@echo "... Quake/net_bsd.s"
	@echo "... Quake/net_dgrm.o"
	@echo "... Quake/net_dgrm.i"
	@echo "... Quake/net_dgrm.s"
	@echo "... Quake/net_loop.o"
	@echo "... Quake/net_loop.i"
	@echo "... Quake/net_loop.s"
	@echo "... Quake/net_main.o"
	@echo "... Quake/net_main.i"
	@echo "... Quake/net_main.s"
	@echo "... Quake/net_udp.o"
	@echo "... Quake/net_udp.i"
	@echo "... Quake/net_udp.s"
	@echo "... Quake/pl_linux.o"
	@echo "... Quake/pl_linux.i"
	@echo "... Quake/pl_linux.s"
	@echo "... Quake/pmove.o"
	@echo "... Quake/pmove.i"
	@echo "... Quake/pmove.s"
	@echo "... Quake/pmovetst.o"
	@echo "... Quake/pmovetst.i"
	@echo "... Quake/pmovetst.s"
	@echo "... Quake/pr_cmds.o"
	@echo "... Quake/pr_cmds.i"
	@echo "... Quake/pr_cmds.s"
	@echo "... Quake/pr_edict.o"
	@echo "... Quake/pr_edict.i"
	@echo "... Quake/pr_edict.s"
	@echo "... Quake/pr_exec.o"
	@echo "... Quake/pr_exec.i"
	@echo "... Quake/pr_exec.s"
	@echo "... Quake/pr_ext.o"
	@echo "... Quake/pr_ext.i"
	@echo "... Quake/pr_ext.s"
	@echo "... Quake/r_alias.o"
	@echo "... Quake/r_alias.i"
	@echo "... Quake/r_alias.s"
	@echo "... Quake/r_brush.o"
	@echo "... Quake/r_brush.i"
	@echo "... Quake/r_brush.s"
	@echo "... Quake/r_part.o"
	@echo "... Quake/r_part.i"
	@echo "... Quake/r_part.s"
	@echo "... Quake/r_part_fte.o"
	@echo "... Quake/r_part_fte.i"
	@echo "... Quake/r_part_fte.s"
	@echo "... Quake/r_sprite.o"
	@echo "... Quake/r_sprite.i"
	@echo "... Quake/r_sprite.s"
	@echo "... Quake/r_world.o"
	@echo "... Quake/r_world.i"
	@echo "... Quake/r_world.s"
	@echo "... Quake/sbar.o"
	@echo "... Quake/sbar.i"
	@echo "... Quake/sbar.s"
	@echo "... Quake/snd_codec.o"
	@echo "... Quake/snd_codec.i"
	@echo "... Quake/snd_codec.s"
	@echo "... Quake/snd_dma.o"
	@echo "... Quake/snd_dma.i"
	@echo "... Quake/snd_dma.s"
	@echo "... Quake/snd_mem.o"
	@echo "... Quake/snd_mem.i"
	@echo "... Quake/snd_mem.s"
	@echo "... Quake/snd_mix.o"
	@echo "... Quake/snd_mix.i"
	@echo "... Quake/snd_mix.s"
	@echo "... Quake/snd_mp3tag.o"
	@echo "... Quake/snd_mp3tag.i"
	@echo "... Quake/snd_mp3tag.s"
	@echo "... Quake/snd_sdl.o"
	@echo "... Quake/snd_sdl.i"
	@echo "... Quake/snd_sdl.s"
	@echo "... Quake/snd_voip.o"
	@echo "... Quake/snd_voip.i"
	@echo "... Quake/snd_voip.s"
	@echo "... Quake/snd_wave.o"
	@echo "... Quake/snd_wave.i"
	@echo "... Quake/snd_wave.s"
	@echo "... Quake/strlcat.o"
	@echo "... Quake/strlcat.i"
	@echo "... Quake/strlcat.s"
	@echo "... Quake/strlcpy.o"
	@echo "... Quake/strlcpy.i"
	@echo "... Quake/strlcpy.s"
	@echo "... Quake/sv_main.o"
	@echo "... Quake/sv_main.i"
	@echo "... Quake/sv_main.s"
	@echo "... Quake/sv_move.o"
	@echo "... Quake/sv_move.i"
	@echo "... Quake/sv_move.s"
	@echo "... Quake/sv_phys.o"
	@echo "... Quake/sv_phys.i"
	@echo "... Quake/sv_phys.s"
	@echo "... Quake/sv_user.o"
	@echo "... Quake/sv_user.i"
	@echo "... Quake/sv_user.s"
	@echo "... Quake/sys_sdl_unix.o"
	@echo "... Quake/sys_sdl_unix.i"
	@echo "... Quake/sys_sdl_unix.s"
	@echo "... Quake/view.o"
	@echo "... Quake/view.i"
	@echo "... Quake/view.s"
	@echo "... Quake/wad.o"
	@echo "... Quake/wad.i"
	@echo "... Quake/wad.s"
	@echo "... Quake/world.o"
	@echo "... Quake/world.i"
	@echo "... Quake/world.s"
	@echo "... Quake/zone.o"
	@echo "... Quake/zone.i"
	@echo "... Quake/zone.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

